name: Snake Eating Contribution

on:
  push:
    branches:
      - main # Adjust the branch name accordingly
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Generate Commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run generate-commits
